# Generated by Django 2.2.4 on 2019-08-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beautify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
