# Generated by Django 2.2.4 on 2019-08-08 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Beautify', '0002_auto_20190808_1846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='featured',
        ),
        migrations.AddField(
            model_name='look',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
