# Generated by Django 2.2.4 on 2019-08-08 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Beautify', '0004_auto_20190808_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='LookItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beautify.Item')),
                ('look', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Beautify.Look')),
            ],
        ),
    ]
